version: "3.9"
services:
  mcri-frontend:
    image: ghcr.io/uomresearchit/mcri-frontend
    depends_on:
      - mcri-backend
    networks:
      mcri:

  mcri-backend:
    image: ghcr.io/uomresearchit/mcri-backend
    volumes:
      - ${SWAG_DIR}/etc/letsencrypt/live/${URL}/privkey.pem:/etc/letsencrypt/live/muo-backend.cs.man.ac.uk/privkey.pem
      - ${SWAG_DIR}/etc/letsencrypt/live/${URL}/fullchain.pem:/etc/letsencrypt/live/muo-backend.cs.man.ac.uk/fullchain.pem
    depends_on:
      swag:
        condition: service_healthy
      mongo:
        condition: service_started
      influx:
        condition: service_started
    networks:
      mcri:

  # container-cron:
  #   image: ghcr.io/uomresearchit/container-cron
  #   environment:
  #     - cron_freq=*/1 * * * *
  #     - cron_cmd=date >> /crontest.csv
  #   networks:
  #     mcri:

  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: mcri
    networks:
      mcri:

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
    networks:
      mcri:
    
  influx:
    image: influxdb:1.8.10
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      INFLUXDB_DB: db0
      INFLUXDB_ADMIN_USER: ${INFLUX_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUX_PASS}
    networks:
      mcri:

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - CERTPROVIDER=zerossl
      - EMAIL=oliver.woolland@manchester.ac.uk
    volumes:
      - ${SWAG_DIR}:/config
      - ./swag_config/default.conf:/config/nginx/site-confs/default.conf
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80 
    networks:
      mcri:
    healthcheck:
      test: ["CMD", "cat", "/etc/letsencrypt/live/${URL}/privkey.pem"]
      interval: 10s
      timeout: 10s
      retries: 5
  
volumes:
  influxdb-storage:

networks:
  mcri:
    driver: bridge
    ipam:
     config:
       - subnet: 172.31.6.0/24
         gateway: 172.31.6.1
